#!/usr/bin/env ruby
# frozen_string_literal: true

require 'openssl'
require 'io/console'

file = 'ubuntu-setup-script.sh'
enc_file = 'docs/ubuntu-setup-script.sh.enc'

if File.exist?(file)
  warn "#{file} が存在するため、デコードできません。"
  exit false
end

begin
  pass = ENV['PASSWD'].chomp

  dec = OpenSSL::Cipher.new('AES-256-CBC')
  dec.decrypt
  dec.pkcs5_keyivgen(pass)

  File.open(enc_file) do |fenc|
    dec_data = dec.update(fenc.read) + dec.final
    File.open(file, 'w') do |fdec|
      fdec.write(dec_data)
    end
  end
rescue OpenSSL::Cipher::CipherError
  warn '共通鍵暗号復号エラー'
  exit false
end

puts 'OK'
