#!/usr/bin/env ruby
# frozen_string_literal: true

require 'openssl'
require 'io/console'

file = 'ubuntu-setup-script.sh'
enc_file = 'docs/ubuntu-setup-script.sh.enc'

print('パスワードを入力してください: ')
pass = $stdin.noecho(&:gets)
pass.chomp!

enc = OpenSSL::Cipher.new('AES-256-CBC')
enc.encrypt
enc.pkcs5_keyivgen(pass)

File.open(file) do |fdec|
  enc_data = enc.update(fdec.read) + enc.final
  File.open(enc_file, 'w') do |fenc|
    fenc.write(enc_data)
  end
end

puts '完了'
